### PR TITLE
Automatically pin newly created tab when there is no pinned tabs

### PR DESCRIPTION
**Pull request by QxQ**
old title: allows the program to create its new tabs pinned
old issue #1

### CODE REVIEW

**Comment by livibetter** [comment]
This is a small bug in this since you named the new option "Always keep 1 tab pinned." Steps to reproduce
1. Have one pinned tab and two unpinned tabs.
2. Close the pinned tab by middle click or Ctrl+W.
3. The two unpinned tabs still unpinned.

It's not "Always."

I really feel this patch is quite problematic and also as I stated in #1, it doesn't totally resolve the accidental close issue by using one pinned tab. Only people who don't know about middle click closing and Ctrl+W can be benefit from this patch. The patch must be generally help most of people and do not create much confusing.

Two tabs might not be good for every even someone people think it's annoying, but so far it's 100% proof beside code injecting which is not 100% (you can't inject certain pages)<del> and despite Alt+F4</del>.

When I said this feature was fine with me, I didn't understand your patch's purpose at all. I thought you just make all opened tabs pinned, which I felt bizarre, but it's fine since it shouldn't have bugs. But the current patch has.

With the reason above and in #1, I probably won't merge. _I am sorry that your effort might have to stay in this pull request._

If you can sort out of the issues or someone else has some way to get around, I would be happily merging them into.

I will leave this open so people can add their inputs.

**Comment by livibetter** [comment]
I need to correct myself. I notice that you now have two tabs, one is pinned. IIRC, someone seemed to leave a comment in web store about similar feature.

Okay, I think this might be fine if you can sort out the issue the "Always" part and have a consistent way when user want to unpin the only pinned tab, what should this extension do? Pin another tab?

If it will only create confusion, then it probably is not a good feature to implement.

**Comment by QxQ** [comment]
I have reworded it like you asked. does it work out?

On Wed, Feb 1, 2012 at 12:25 PM, Yu-Jie Lin <
reply@reply.github.com

**Comment by livibetter** [comment]
I was afraid that you would do such thing, i.e. changing the name of the option, and you did it.

Well, I will release this anyway and put a Feedback link next to this option. Because I don't want people can't understand it.

**Comment by livibetter** [comment]
Please feel free to give your feedback of this option, _Automatically pin newly created tab when there is no pinned tabs_.

You can still comment when this issue is closed, be sure to read #1 if you want to know about the history of this option.

**Pull request closed without merging**
