### PR TITLE
I added a check box that lets you make the new tabs that this extension makes, pinned.

### PR DESCRIPTION
**Pull request by QxQ**

### CODE REVIEW

**Comment by livibetter** [comment]
I am afraid that I must reject this commits set, the reason is not the feature got rejected but the commits are a little messy.

2e12c8c is fine, except my variable naming convention is `is_pinned`. (although Chrome API is camelCase)
e359366 has some testing code (alert function), please clean up. I haven't read the modified code.
37b2d00 please don't use commit as comment. The committed content is going into repo. Leave a comment in issue if you have questions.

If I understand correctly, you are trying to make opened tabs by KLTT to be pinned tabs. I am okay with this. However, something you said in 37b2d00 makes me feel uncertain:

> if you unpin a tab, what should happen is a new pinned tab appears in it's place. what happens is nothing.

I don't understand at all. Could you explain again? and you mention you want to add a screenshot, I suppose it's new options page? It's fine, you don't really need to update screenshot. I can put new info in extension's description box on web store.

I will leave this open for communication, leave comments if you have question. Please restart your work, don't work on top of your current commits. Open a new pull request and close this one when you clean up your code.

(Little typo or error is fine, no need to be perfect, I can fix in my end. But this commit set has too many and unclear to me)

**Comment by QxQ** [comment]
thanks you for the reply. I have fixed what you have specified, but haven't
uploaded the changes yet.

what I meant when I said "if you unpin a tab, what should happen is a new
pinned tab appears in it's place. what happens is nothing." is this:
if a tab is pinned, I allow that to be the only tab open, because it
can't accidentally be closed, (you have to right click and say close, or
unpin it then close it). the only problem I have with this is if the user
does unpin it, it becomes the only tab in the browser, and I can't find any
way to make an event fire up when this happens to create a new pinned tab.
of coarse this only happens when they have the new option checked. if you
still don't understand me, I can send a screen capture movie of how this
works.

I did some research and there doesn't seem to be an unpin event. so from
what I understand, I only have two options, make it so there always has to
be two tabs open, or let the user be able to unpin the single tab then
close it.

On Tue, Jan 31, 2012 at 6:31 PM, Yu-Jie Lin <
reply@reply.github.com

**Comment by livibetter** [comment]
After read your reply, I am sure I didn't understand your patch (the purpose of the patch) at first place. Correct me I still misunderstand:

Your patch is to make a pinned tab and it's basically the last one tab in the Chrome, because it's pinned so it can prevent user accidentally close Chrome. It can do so because there is no 'X' on the pinned tab.

If I describe correctly, I think this convinces me not to merge your patch because:
- Pinned tab can still be closed by middle-click.
- Pinned tab can still be close by pressing Ctrl+W.

The only thing it prevents it the closing by clicking on the 'X'.

Despite the issue above, I believe this patch might create more confusing when user tries to unpin and still seeing pinned tab. It's more like being an unfinished patch due to the lack of API to achieve what you want to do.

**Comment by QxQ** [comment]
I understand and have taken out the extra feature. thank you for
your patience, I have posted the code changed the way you want.

On Tue, Jan 31, 2012 at 10:20 PM, Yu-Jie Lin <
reply@reply.github.com

**Pull request closed without merging**
